artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Brymahh/class-acme-pred/raw/refs/heads/main/research/dataset.csv
  local_data_file: artifacts/data_ingestion/dataset.csv
  #unzip_dir: artifacts/data_ingestion